/* tslint:disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();
const environment = argv.environment;


function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote environment data to ${targetPath}`);
      console.log(`App: ${appAPI}`);
      console.log(`Station: ${stnAPI}`);
    }
  });
}

// Providing path to the `environments` directory
const envDirectory = './src/environments';
const appAPI = process.env.AMBIENT_API_KEY;
const stnAPI = process.env.STATION_API_KEY

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

// Creates the `environment.prod.ts` and `environment.ts` files 
// if they do not exist
// writeFileUsingFS('./src/environments/environment.prod.ts', '');
// writeFileUsingFS('./src/environments/environment.ts', '');


// Checks whether command line argument of `prod` was provided signifying production mode
const isProduction = environment === 'prod';

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was auto-generated by dynamically running 
  // setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: ${isProduction},
    AMBIENT_API_KEY: '${appAPI}',
    CAVANT_DRIVE_WX: '${stnAPI}'
  };
`;

// appending data into the target file
writeFileUsingFS(targetPath, environmentFileContent); 

/* tslint:enable */