/* tslint:disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

const path = require('path');
let thePath = path.resolve(__dirname, '../.env');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') })

const environment = argv.environment;

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`Wrote environment data to ${targetPath}`);
    }
  });
}

// Providing path to the 'environments'  directory
const envDirectory = './src/environments';
const apiKey = process.env.apiKey;
const applicationKey = process.env.applicationKey;

// creates the 'environments' directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

// Checks whether command line argument of 'prod' was provided signifying production mode
const isProduction = environment === 'prod';

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was auto-generated by dynamically running 
  // setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: ${isProduction},
    applicationKey: '${applicationKey}',
    apiKey: '${apiKey}'
  };
`;

// appending data into the target file
writeFileUsingFS(targetPath, environmentFileContent); 

/* tslint:enable */